version: '3.1'
services:
  mysql1:
    hostname: "mysql1"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql1pass
    ports:
      - "${listening_ip}:3306:3306"
    volumes:
      - ${wh_home}/data/mysql1/data:/var/lib/mysql

