version: '3.1'
services:
  mysql2-e:
    hostname: "mysql2-e"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql2epass
    ports:
      - "${bind_ip}:3402:3306"
    volumes:
      - ${wh_home}/extra/data/mysql2-e/data:/var/lib/mysql

