version: '3.1'
services:
  mysql1-e:
    hostname: "mysql1-e"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql1epass
    ports:
      - "${bind_ip}:3401:3306"
    volumes:
      - ${wh_home}/extra/data/mysql1-e/data:/var/lib/mysql

