#!/bin/bash

echo "**** Starting: [runner1] ****"
echo
echo "--- ENV ---------------------"
echo "bind_ip: ${bind_ip}"
echo "-----------------------------"

while true; do
    /init_mysql1
    sleep 1
done
